### ISSUE TITLE
Write Python/Perl scripts running the static analyser per patch

### ISSUE THREAD

**Issue by mamtashukla** [alice-sieve/Linux-Kernel#15]
picked from a tree.

**Comment by mamtashukla** [comment]
@tapaswenipathak  I attempted to write the script and I have mentioned issue in comment.
https://gist.github.com/mamtashukla/9469c3eec9a3ebb14eae8291cc4dfd8c

**Comment by tapaswenipathak** [comment]
On Fri, Jul 19, 2019 at 12:22 AM Mamta <notifications@github.com> wrote:
>
> @tapaswenipathak I attempted to write the script and I have mentioned issue in comment.
>

Mamta, add as a branch mamta-staticanalyser branch and PR, I will let
people review.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
