### ISSUE TITLE
Kernel APIs

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Linux-Kernel#27]
@Armorer96 

As discussed, you should grep as per

![kernel-api](https://user-images.githubusercontent.com/4143778/58302865-e481df00-7e0a-11e9-8724-80878f4c1c0c.png)

I will write grep/awk commands as well.

**Comment by tapaswenipathak** [comment]
Sorry for the bad hand writing, we can have a call if you feel like.

**Comment by tapaswenipathak** [comment]
Sorry for the bad hand writing, feel free in scheduling a call.

**Comment by mamtashukla** [comment]
Thank you for resolving my confusion about APIs. 
Sure, I will definitely schedule a call, if stuck again.
