### ISSUE TITLE
Grep commands table

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Linux-Kernel#41]
@mamtashukla Add the grep commands table for APIs in a day, I will let people run them on more rc and mainline kernel versions.

**Comment by tapaswenipathak** [comment]
ping

**Comment by mamtashukla** [comment]
Adding the remaining APIs that you have mentioned - https://github.com/alice-sieve/Linux-Kernel/pull/42#pullrequestreview-244618338
