### ISSUE TITLE
Finishing API calls plus grep commands

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Linux-Kernel#50]
Complete in a day.

**Comment by mamtashukla** [comment]
Completed the table with all APIs -https://github.com/alice-sieve/Linux-Kernel/pull/54 .
But having conflict for merging,

**Comment by tapaswenipathak** [comment]
On Wed, Jun 5, 2019 at 4:00 PM Mamta <notifications@github.com> wrote:
>
> Completed the table with all APIs -#54 .
> But having merging issues,

Great! Pinged in Slack channel.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
