### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Linux-Kernel#55]
Every HTML file should be having a line per file having what the columns has.

**Comment by mamtashukla** [comment]
Updated html file of occurrences of API in Kernel:
https://github.com/alice-sieve/Linux-Kernel/pull/63
https://github.com/alice-sieve/Linux-Kernel/pull/62
https://github.com/alice-sieve/Linux-Kernel/pull/61
https://github.com/alice-sieve/Linux-Kernel/pull/60
https://github.com/alice-sieve/Linux-Kernel/pull/59
https://github.com/alice-sieve/Linux-Kernel/pull/58
https://github.com/alice-sieve/Linux-Kernel/pull/57
https://github.com/alice-sieve/Linux-Kernel/pull/56
