### ISSUE TITLE
spinics: Parse mailing list for mail having a kernel patch

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Linux-Kernel#72]
spinics mailing list looks like

<img width="1129" alt="Screen Shot 2019-06-18 at 5 47 14 AM" src="https://user-images.githubusercontent.com/4143778/59644867-7a9bf180-918c-11e9-802e-a8a3d9506560.png">

I think anything having [PATCH] can be parsed.

**Comment by code-monk08** [comment]
only those mailing lists have to be parsed which are present in the organized table here : [73](https://github.com/alice-sieve/Linux-Kernel/issues/73) or entire lists from https://www.spinics.net/lists/ have to be parsed?

**Comment by bymayanksingh** [comment]
pushed https://github.com/alice-sieve/Linux-Kernel/tree/patch-scrapercode-monk08, closing.
