### ISSUE TITLE
Static Analyzers + LDV for race conditions findings Installation

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Linux-Kernel#89]
You would require installing 

- Smatch
- Sparse
- LDV
- https://www.researchgate.net/publication/297756034_DRDDR_a_lightweight_method_to_detect_data_races_in_Linux_kernel

Create a output file.

Please refer
- https://github.com/coccinelle/faults-in-Linux/tree/new.hybrid
- https://github.com/tapaswenipathak/Linux-Kernel-Infer

I will review every FP/Bug and for any questions if you have. These studies are very interesting, let me know if you have any questions.

**Comment by deyachatterjee** [comment]
Kindly stop assigning me to issues. I am not pursuing the work this time. Hope you understand. Thanks.
