### ISSUE TITLE
Create a doc from RaceHound findings

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/Linux-Kernel#90]
List
- callback invocations
- Parallel Excecution
- Interruptions
- Workqueue callbacks
- Synchronization primitives
- Scope and Path conditions

Merges after I review.

**Comment by Aashi15bansal** [comment]
https://paper.dropbox.com/doc/Research-RaceHound--AhZh02fjrHtOqFMwC8IKl~AWAg-6iX3eDMasSj0Ih07zskCr

**Comment by tapaswenipathak** [comment]
Warnings done?
